name: rating_summary
description: Create a summary statistic Widget to display the rating and average rating of a product.
version: 1.0.2+1
repository: https://github.com/floodoo/rating_summary

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=2.11.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
